/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.DAO.NhanVienDAO;
import com.edusys.Entity.NhanVien;
import com.edusys.model.nhanVienDAO;
import static com.edusys.ui.loginJDialog.cointindexconect;
import static com.edusys.ui.loginJDialog.txtTaiKhoan;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DangNhapMDI extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapMDI
     */
    public DangNhapMDI() {
        initComponents();
        setLocationRelativeTo(null);
        innit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cboShowMatKhau = new javax.swing.JCheckBox();
        lblAnh = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Mật khẩu");

        cboShowMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboShowMatKhauActionPerformed(evt);
            }
        });

        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setText("ẢNH");

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });
        txtTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTaiKhoanKeyReleased(evt);
            }
        });

        jLabel2.setText("Tài Khoản");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMatKhau)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnDangNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnHuy)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboShowMatKhau)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboShowMatKhau))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDangNhap)
                            .addComponent(btnHuy)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboShowMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboShowMatKhauActionPerformed
        if (cboShowMatKhau.isSelected()) {
            cboShowMatKhau.setIcon(new ImageIcon(new ImageIcon(loginJDialog.class.getResource("/com/edusys/icon/eye.png")).getImage().getScaledInstance(cboShowMatKhau.getWidth(), cboShowMatKhau.getHeight(), 1)));
            txtMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('*');
            cboShowMatKhau.setIcon(new ImageIcon(new ImageIcon(loginJDialog.class.getResource("/com/edusys/icon/visibility.png")).getImage().getScaledInstance(cboShowMatKhau.getWidth(), cboShowMatKhau.getHeight(), 1)));
        }
    }//GEN-LAST:event_cboShowMatKhauActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (txtTaiKhoan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa nhập tài khoản");
            txtTaiKhoan.requestFocus();
        } else if (txtMatKhau.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa nhập mật khẩu");
            txtMatKhau.requestFocus();
        } else {
            cointindexconect++;
            dangNhap2();
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Bạn muốn kết thúc ứng dụng");
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        //        if(MsgBox.){}
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    private void txtTaiKhoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaiKhoanKeyReleased
        txtTaiKhoan.setText(txtTaiKhoan.getText().toUpperCase());
    }//GEN-LAST:event_txtTaiKhoanKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnHuy;
    private javax.swing.JCheckBox cboShowMatKhau;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JPasswordField txtMatKhau;
    public static javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
    protected static int cointindexconect;
    protected static int contLogin;
    nhanVienDAO nvDAO1 = new nhanVienDAO();
    protected static boolean checkVaiTro;
    NhanVienDAO nvDao = new NhanVienDAO();
    boolean checkDangNhap;
    private void innit() {
        cboShowMatKhau.setIcon(new ImageIcon(new ImageIcon(loginJDialog.class.getResource("/com/edusys/icon/visibility.png")).getImage().getScaledInstance(cboShowMatKhau.getWidth(), cboShowMatKhau.getHeight(), 1)));
        lblAnh.setIcon(new ImageIcon(new ImageIcon(loginJDialog.class.getResource("/com/edusys/icon/security.png")).getImage().getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), 0)));
//        nvDAO1.queryListNhanVien();
    }

    void dangNhap2() {

        NhanVien nv = nvDao.selectById(txtTaiKhoan.getText());
        System.out.println("nhân viên " + nv);
        if (nv == null) {
            JOptionPane.showMessageDialog(this, "sai tài khoản");
            txtTaiKhoan.requestFocus();
            cointindexconect = 0;
        } else if (!nv.getMatkhau().equals(txtMatKhau.getText())) {
            JOptionPane.showMessageDialog(this, "sai mật khẩu");
            txtMatKhau.requestFocus();
            cointindexconect = 0;
        } else {
            if (nv.isFirstlogin() == true) {
//                JOptionPane.showMessageDialog(this, "do phần mềm đang nâng cấp nên tạm thời đóng chức năng này");
                System.out.println("show man doi mat khau");
                dispose();
                JOptionPane.showMessageDialog(this, "Bạn Cần Đổi mật khẩu lần cho lần đầu tiên đăng nhập");
                new firstLogIn(new EduSysJFrame(), true).setVisible(true);
            } else {
                checkVaiTro = nv.isVaitro();
                System.out.println("dang nhap thanh cong");
                this.dispose();
                if (cointindexconect > 1 || contLogin ==1) {
                    System.out.println("danh nhap");
                    new EduSysJFrame().setVisible(true);
                }
            }
        }
    }
}
