/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import static com.edusys.Connect.Connect.cnt;
import com.edusys.untils.Ximg;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author DELL
 */
public class EduSysJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EduSysJFrame
     */
    public EduSysJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        innit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lplStatus = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        bntThoat = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel(){
            URL erlicon = EduSysJFrame.class.getResource("/com/edusys/icon/bkgr.jpg");
            Image img = new ImageIcon(erlicon).getImage();
            ImageIcon icon = new ImageIcon(img);
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, this);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        mnThoat = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        mnDoiMatKhau = new javax.swing.JMenuItem();
        mnuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnChuyenDe = new javax.swing.JMenuItem();
        mnKhoaHoc = new javax.swing.JMenuItem();
        mnHocVien = new javax.swing.JMenuItem();
        mnNguoiHoc = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuNhanVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuBangDiem = new javax.swing.JMenuItem();
        mnuNguoiHoc = new javax.swing.JMenuItem();
        mnuDiemChuyenDe = new javax.swing.JMenuItem();
        mnuDoanhTHu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuHuongDan = new javax.swing.JMenuItem();
        munGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÍ ĐÀO TẠO EDUSYS");

        lplStatus.setAutoscrolls(true);

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/info.png"))); // NOI18N
        lblStatus.setText("Status");

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/wall-clock.png"))); // NOI18N
        lblDongHo.setText("Đồng hồ");

        javax.swing.GroupLayout lplStatusLayout = new javax.swing.GroupLayout(lplStatus);
        lplStatus.setLayout(lplStatusLayout);
        lplStatusLayout.setHorizontalGroup(
            lplStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lplStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addGap(26, 26, 26))
        );
        lplStatusLayout.setVerticalGroup(
            lplStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lplStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lplStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblDongHo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        btnDangXuat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/24px/exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        bntThoat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bntThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/24px/power.png"))); // NOI18N
        bntThoat.setText("Thoát");
        bntThoat.setFocusable(false);
        bntThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntThoat.setMargin(new java.awt.Insets(2, 20, 2, 14));
        bntThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(bntThoat);
        jToolBar1.add(jSeparator2);

        btnChuyenDe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/24px/clipboard.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên Đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyenDe);

        btnNguoiHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/24px/group.png"))); // NOI18N
        btnNguoiHoc.setText("Người Học");
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNguoiHoc);

        btnKhoaHoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/24px/teaching.png"))); // NOI18N
        btnKhoaHoc.setText("Khóa Học");
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhoaHoc);

        btnHocVien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/24px/graduated.png"))); // NOI18N
        btnHocVien.setText("Học Viên");
        btnHocVien.setFocusable(false);
        btnHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocVien.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnHocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHocVien);
        jToolBar1.add(jSeparator1);

        btnHuongDan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/24px/earth.png"))); // NOI18N
        btnHuongDan.setText("Hướng Dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHuongDan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );

        jMenuBar1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(272, 40));

        mnThoat.setText("Hệ thống");
        mnThoat.setIconTextGap(10);

        mnuDangXuat.setText("Đăng Xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        mnThoat.add(mnuDangXuat);

        mnDoiMatKhau.setText("Đổi mật khẩu");
        mnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoiMatKhauActionPerformed(evt);
            }
        });
        mnThoat.add(mnDoiMatKhau);

        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnThoat.add(mnuThoat);

        jMenuBar1.add(mnThoat);

        jMenu2.setText("Quản lí");

        mnChuyenDe.setText("Chuyên Đề");
        mnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChuyenDeActionPerformed(evt);
            }
        });
        jMenu2.add(mnChuyenDe);

        mnKhoaHoc.setText("Khóa Học");
        mnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKhoaHocActionPerformed(evt);
            }
        });
        jMenu2.add(mnKhoaHoc);

        mnHocVien.setText("Học viên");
        mnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHocVienActionPerformed(evt);
            }
        });
        jMenu2.add(mnHocVien);

        mnNguoiHoc.setText("Người Học");
        mnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNguoiHocActionPerformed(evt);
            }
        });
        jMenu2.add(mnNguoiHoc);
        jMenu2.add(jSeparator3);

        mnuNhanVien.setText("Nhân Viên");
        mnuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(mnuNhanVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mnuBangDiem.setText("Bảng Điểm");
        mnuBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBangDiemActionPerformed(evt);
            }
        });
        jMenu3.add(mnuBangDiem);

        mnuNguoiHoc.setText("Lượng Người Học");
        mnuNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNguoiHocActionPerformed(evt);
            }
        });
        jMenu3.add(mnuNguoiHoc);

        mnuDiemChuyenDe.setText("Điểm Chuyên Đề");
        mnuDiemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDiemChuyenDeActionPerformed(evt);
            }
        });
        jMenu3.add(mnuDiemChuyenDe);

        mnuDoanhTHu.setText("Doanh Thu");
        mnuDoanhTHu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoanhTHuActionPerformed(evt);
            }
        });
        jMenu3.add(mnuDoanhTHu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mnuHuongDan.setText("Hướng Dẫn");
        mnuHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHuongDanActionPerformed(evt);
            }
        });
        jMenu4.add(mnuHuongDan);

        munGioiThieu.setText("Giới thiệu");
        munGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munGioiThieuActionPerformed(evt);
            }
        });
        jMenu4.add(munGioiThieu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lplStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1229, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lplStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        EduSysJFrame.this.dispose();
        loginJDialog.txtTaiKhoan.setText(null);
        login.cointindexconect++;
        loginJDialog.contLogin=1;
        new loginJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void bntThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThoatActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "bạn có muốn thoát khỏi chương trình không");
        if (i == JOptionPane.YES_OPTION) {
            try {
                cnt.close();
            } catch (SQLException ex) {
                Logger.getLogger(EduSysJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }
    }//GEN-LAST:event_bntThoatActionPerformed

    private void mnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNguoiHocActionPerformed
        lblStatus.setText("Quản Lí " + btnNguoiHoc.getText());
        new QuanLi_NguoiHocDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnNguoiHocActionPerformed

    private void mnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHocVienActionPerformed
        lblStatus.setText("Quản Lí " + btnHocVien.getText());
        new QuanLi_HocVienJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnHocVienActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        lblStatus.setText("Quản Lí " + btnChuyenDe.getText());
        new QuanLy_ChuyenDe(this, true).setVisible(true);

    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        lblStatus.setText("Quản Lí " + btnNguoiHoc.getText());
        new QuanLi_NguoiHocDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        lblStatus.setText("Quản Lí " + btnKhoaHoc.getText());
        new QuanLi_KhoaHocJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        lblStatus.setText("Quản Lí " + btnHocVien.getText());
        new QuanLi_HocVienJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        lblStatus.setText(btnHuongDan.getText());
        new HuongDanJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void mnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoiMatKhauActionPerformed
        lblStatus.setText("Quản Lí " + mnDoiMatKhau.getText());
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnDoiMatKhauActionPerformed

    private void mnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKhoaHocActionPerformed
        lblStatus.setText("Quản Lí " + btnKhoaHoc.getText());
        new QuanLi_KhoaHocJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnKhoaHocActionPerformed

    private void mnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChuyenDeActionPerformed
        lblStatus.setText("Quản Lí " + btnChuyenDe.getText());
        new QuanLy_ChuyenDe(this, true).setVisible(true);

    }//GEN-LAST:event_mnChuyenDeActionPerformed

    private void mnuHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHuongDanActionPerformed
        lblStatus.setText("Quản Lí " + mnuHuongDan.getText());
        new HuongDanJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnuHuongDanActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        EduSysJFrame.this.dispose();
        login.cointindexconect++;
        new loginJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuDiemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDiemChuyenDeActionPerformed
        lblStatus.setText("Quản Lí " + mnuNguoiHoc.getText());
        tabThongKe =2;
        new QuanLi_ThongKe(this, true).setVisible(true);
    }//GEN-LAST:event_mnuDiemChuyenDeActionPerformed

    private void munGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munGioiThieuActionPerformed
        lblStatus.setText(munGioiThieu.getText());
        new gioiThieuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_munGioiThieuActionPerformed
    public static int tabThongKe;
    private void mnuBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBangDiemActionPerformed
        lblStatus.setText("Quản Lí " + mnuDiemChuyenDe.getText());
        tabThongKe = 0;
        new QuanLi_ThongKe(this, true).setVisible(true);
    }//GEN-LAST:event_mnuBangDiemActionPerformed

    private void mnuNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNguoiHocActionPerformed
        lblStatus.setText("Quản Lí " + mnuNguoiHoc.getText());
        tabThongKe =1;
        new QuanLi_ThongKe(this, true).setVisible(true);
    }//GEN-LAST:event_mnuNguoiHocActionPerformed

    private void mnuDoanhTHuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoanhTHuActionPerformed
        lblStatus.setText("Quản Lí " + mnuDoanhTHu.getText());
        tabThongKe =3;
        new QuanLi_ThongKe(this, true).setVisible(true);
    }//GEN-LAST:event_mnuDoanhTHuActionPerformed

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        try {
            cnt.close();
        } catch (SQLException ex) {
            Logger.getLogger(EduSysJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mnuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNhanVienActionPerformed
        lblStatus.setText(mnuNhanVien.getText());
        new QuanLi_NhanVienJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mnuNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EduSysJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntThoat;
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongHo;
    protected static javax.swing.JLabel lblStatus;
    private javax.swing.JPanel lplStatus;
    private javax.swing.JMenuItem mnChuyenDe;
    private javax.swing.JMenuItem mnDoiMatKhau;
    private javax.swing.JMenuItem mnHocVien;
    private javax.swing.JMenuItem mnKhoaHoc;
    private javax.swing.JMenuItem mnNguoiHoc;
    private javax.swing.JMenu mnThoat;
    private javax.swing.JMenuItem mnuBangDiem;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDiemChuyenDe;
    private javax.swing.JMenuItem mnuDoanhTHu;
    private javax.swing.JMenuItem mnuHuongDan;
    private javax.swing.JMenuItem mnuNguoiHoc;
    private javax.swing.JMenuItem mnuNhanVien;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JMenuItem munGioiThieu;
    // End of variables declaration//GEN-END:variables
//    backgroungGirlXinh
    loginJDialog login;
    chaoJDialog chaolg;

    private void innit() {
        clock();
        lblStatus.setText("Hệ thống quản lí đào tạo EduSys");
        this.setIconImage(Ximg.getAppicon());
        if (login.cointindexconect < 1) {
            new chaoJDialog(this, true).setVisible(true);
//            new DangNhapJInternalFrame().setVisible(true);
            System.out.println("check");
            new loginJDialog(this, true).setVisible(true);
        }
        // phân quyền
        if (!loginJDialog.checkVaiTro) {
            jMenu3.setEnabled(false);
            mnuNhanVien.setEnabled(false);
        }
    }

    private void clock() {
        Timer time = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                Date date = new Date();
                lblDongHo.setText(sdf.format(date.getTime()));
            }
        });
        time.start();
    }

//    jPanel1  = new javax.swing.JPanel() {
//        URL erlicon = EduSysJFrame.class.getResource("/com/edusys/icon/bkgr.jpg");
//        Image img = new ImageIcon(erlicon).getImage();
//        ImageIcon icon = new ImageIcon(img);
//
//        public void paintComponent(Graphics g) {
//            Dimension d = getSize();
//            g.drawImage(icon.getImage(), 0, 0, d.width, d.height, this);
//            setOpaque(false);
//            super.paintComponent(g);
//        }
//    };
}
