/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.Entity.KhoaHoc;
import com.edusys.Entity.NhanVien;
import com.edusys.Entity.ChuyenDe;
import com.edusys.DAO.KhoaHocDAO;
import com.edusys.DAO.NhanVienDAO;
import com.edusys.DAO.ChuyenDeDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QuanLi_KhoaHocJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLi_KhoaHocJDialog
     */
    KhoaHocDAO khDAO = new KhoaHocDAO();
    NhanVienDAO nvDAO = new NhanVienDAO();
    ChuyenDeDAO cdDAO = new ChuyenDeDAO();
    DefaultTableModel model;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();
    int index;

    public QuanLi_KhoaHocJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tblKhoaHoc.getModel();
        btnthem.setEnabled(false);
        if (!loginJDialog.checkVaiTro) {
            btnXoa.setEnabled(false);
        }
        fillTotable();
        fillCboChuyenDe();
        System.out.println(listKhoaHoc);
        System.out.println(listNhanVien);
        System.out.println(listChuyenDe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNguoiTao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnthem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        cboChuyenDe = new javax.swing.JComboBox<>();
        txtNgayKhaiGiang = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtTimKhiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhoaHoc = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys - Quản Lí Khóa Học");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chuyên đề");

        txtHocPhi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Học Phí");

        txtNguoiTao.setEditable(false);
        txtNguoiTao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNguoiTao.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Người Tạo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Khai Giảng");

        txtNgayTao.setEditable(false);
        txtNgayTao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgayTao.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ngày Tạo");

        txtThoiLuong.setEditable(false);
        txtThoiLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtThoiLuong.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Thời Lượng (giờ)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mô tả");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        btnthem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("|<");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("<<");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText(">>");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText(">|");

        cboChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChuyenDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtHocPhi)
                            .addComponent(txtNguoiTao)
                            .addComponent(cboChuyenDe, 0, 281, Short.MAX_VALUE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(txtNgayKhaiGiang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtThoiLuong)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayKhaiGiang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cập Nhật", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        txtTimKhiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKhiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKhiemActionPerformed(evt);
            }
        });
        txtTimKhiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKhiemKeyReleased(evt);
            }
        });
        jPanel3.add(txtTimKhiem);

        tblKhoaHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khóa Học", "Thời Lượng ", "Học Phí", "Khải Giảng", "Người Tạo", "Ngày Tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhoaHoc.setRowHeight(24);
        tblKhoaHoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoaHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhoaHoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel4.add(jTextField2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKhiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKhiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKhiemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        EduSysJFrame.lblStatus.setText("Hệ thống quản lí đào tạo EduSys");
    }//GEN-LAST:event_formWindowClosed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();
        btnthem.setEnabled(true);
        index = -1;
    }//GEN-LAST:event_btnMoiActionPerformed

    private void cboChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChuyenDeActionPerformed
        for (ChuyenDe cd : listChuyenDe) {
            if (cd.getTenChuyenDe().equals(cboChuyenDe.getSelectedItem())) {
                System.out.println("ten chuyen de" + cd.getTenChuyenDe());
                txtThoiLuong.setText(cd.getThoiLuong());
                break;
            }
        }
    }//GEN-LAST:event_cboChuyenDeActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        if (validateForm()) {
            insertKhoaHoc(getKhoaHoc());
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void tblKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoaHocMouseClicked
        index = tblKhoaHoc.getSelectedRow();
        int ma = (int) tblKhoaHoc.getValueAt(tblKhoaHoc.getSelectedRow(), 0);
        showForm(ma);
        btnthem.setEnabled(false);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_tblKhoaHocMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        int ma = (int) tblKhoaHoc.getValueAt(index, 0);
        update(getKhoaHoc(), ma);
        JOptionPane.showMessageDialog(this, "sua ok");

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int ma = (int) tblKhoaHoc.getValueAt(tblKhoaHoc.getSelectedRow(), 0);
        int i = JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn xóa khóa học này không");
        if (i == JOptionPane.YES_OPTION) {
            for (KhoaHoc kh : listKhoaHoc) {
                if (kh.getMaKhoaHoc() == ma) {
                    Xoa(kh);
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKhiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKhiemKeyReleased
        int ma=0;
        if(!txtTimKhiem.getText().isEmpty()){
            ma = Integer.parseInt(txtTimKhiem.getText());
        }
        timKiem(ma);
    }//GEN-LAST:event_txtTimKhiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLi_KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLi_KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLi_KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLi_KhoaHocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLi_KhoaHocJDialog dialog = new QuanLi_KhoaHocJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnthem;
    private javax.swing.JComboBox<String> cboChuyenDe;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblKhoaHoc;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextArea txtMoTa;
    private com.toedter.calendar.JDateChooser txtNgayKhaiGiang;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtThoiLuong;
    private javax.swing.JTextField txtTimKhiem;
    // End of variables declaration//GEN-END:variables
    List<KhoaHoc> listKhoaHoc = khDAO.selectAll();
    List<NhanVien> listNhanVien = nvDAO.selectAll();
    List<ChuyenDe> listChuyenDe = cdDAO.selectAll();

    private void fillTotable() {
        model.setRowCount(0);
        for (KhoaHoc kh : listKhoaHoc) {
            if (kh.isDeleteAt() == true) {
                String ten = "";
                for (NhanVien nv : listNhanVien) {
                    if (nv.getManhanvien().equals(kh.getMaNhanVien())) {
                        ten = nv.getHoten();
                        break;
                    }
                }
                model.addRow(new Object[]{kh.getMaKhoaHoc(),
                    kh.getThoiLuong(),
                    kh.getHocPhi(),
                    kh.getNgayKhaiGiang(),
                    ten,
                    kh.getNgayTao()});
            }
        }
    }

    private void fillCboChuyenDe() {
        jTabbedPane1.setSelectedIndex(0);
        for (ChuyenDe cd : listChuyenDe) {
            cboChuyenDe.addItem(cd.getTenChuyenDe());
        }
    }

    private void showForm(int ma) {
        for (KhoaHoc kh : listKhoaHoc) {
            if (kh.getMaKhoaHoc() == ma) {
                cboChuyenDe.setSelectedItem(kh.getMaChuyenDe());
                txtHocPhi.setText(kh.getHocPhi() + "");
                txtMoTa.setText(kh.getGhiChu());
                txtNgayKhaiGiang.setDate(kh.getNgayKhaiGiang());
                txtNgayTao.setText(kh.getNgayTao() + "");
                txtThoiLuong.setText(kh.getThoiLuong());
                for (NhanVien nv : listNhanVien) {
                    if (nv.getManhanvien().equals(kh.getMaNhanVien())) {
                        txtNguoiTao.setText(nv.getHoten());
                        break;
                    }
                }
                break;
            }
        }
    }

    private KhoaHoc getKhoaHoc() {
        KhoaHoc kh = new KhoaHoc();
        for (ChuyenDe cd : listChuyenDe) {
            if (cboChuyenDe.getSelectedItem().equals(cd.getTenChuyenDe())) {
                kh.setMaChuyenDe(cd.getMaChuyenDe());
                break;
            } else {
                System.out.println("sai");
            }
        }
        kh.setHocPhi(Integer.parseInt(txtHocPhi.getText()));
        kh.setThoiLuong(txtThoiLuong.getText());
        kh.setNgayKhaiGiang(txtNgayKhaiGiang.getDate());
        kh.setNgayTao(new java.util.Date(date.getTime()));
        kh.setMaNhanVien(loginJDialog.txtTaiKhoan.getText());
        kh.setGhiChu(txtMoTa.getText());
        kh.setDeleteAt(true);

        return kh;
    }

    private void clearForm() {
        for (NhanVien nv : listNhanVien) {
            if (nv.getManhanvien().equals(loginJDialog.txtTaiKhoan.getText())) {
                txtNguoiTao.setText(nv.getHoten());
                txtNgayTao.setText(sdf.format(date.getTime()));
                break;
            }
        }
        txtHocPhi.setText("");
    }

    private void insertKhoaHoc(KhoaHoc getKH) {
        try {
            khDAO.insert(getKH);
            listKhoaHoc.add(getKH);
            model.addRow(new Object[]{getKH.getMaKhoaHoc(),
                getKH.getThoiLuong(),
                getKH.getHocPhi(),
                getKH.getNgayKhaiGiang(),
                getKH.getMaNhanVien(),
                getKH.getNgayTao()});
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("loi insert khoa hoc");
        }
    }

    private boolean validateForm() {
        if (txtHocPhi.getText().isEmpty()) {
            txtHocPhi.requestFocus();
            return false;
        }
        if (txtHocPhi.getText().isEmpty()) {
            txtHocPhi.requestFocus();
            return false;
        }
        return true;
    }

    private void Xoa(KhoaHoc getKH) {
        try {
            khDAO.deleteDAO(getKH);
            model.removeRow(index);
        } catch (Exception e) {
            System.out.println("loi k xoa dc khoa hoc");
        }
    }

    private void update(KhoaHoc getKH, int ma) {
        try {
            khDAO.update(getKH, ma);
            model.setValueAt(getKH.getHocPhi(), index, 1);
            model.setValueAt(getKH.getThoiLuong(), index, 2);
            model.setValueAt(getKH.getNgayKhaiGiang(), index, 3);
            for (int i = 0; i < listKhoaHoc.size(); i++) {
                if (listKhoaHoc.get(i).getMaKhoaHoc() == ma) {
                    listKhoaHoc.get(i).setMaChuyenDe(getKH.getMaChuyenDe());
                    listKhoaHoc.get(i).setHocPhi(getKH.getHocPhi());
                    listKhoaHoc.get(i).setThoiLuong(getKH.getThoiLuong());
                    listKhoaHoc.get(i).setNgayKhaiGiang(getKH.getNgayKhaiGiang());
                    listKhoaHoc.get(i).setGhiChu(getKH.getGhiChu());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void timKiem(int ma) {
        model.setRowCount(0);
        for (KhoaHoc kh : listKhoaHoc) {
            if (kh.getMaKhoaHoc() == ma) {
                if (kh.isDeleteAt() == true) {
                    String ten = "";
                    for (NhanVien nv : listNhanVien) {
                        if (nv.getManhanvien().equals(kh.getMaNhanVien())) {
                            ten = nv.getHoten();
                            break;
                        }
                    }
                    model.addRow(new Object[]{kh.getMaKhoaHoc(),
                        kh.getThoiLuong(),
                        kh.getHocPhi(),
                        kh.getNgayKhaiGiang(),
                        ten,
                        kh.getNgayTao()});
                }
            }

        }
        if(txtTimKhiem.getText().isEmpty()){
            fillTotable();
        }
    }
}
