/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.jdbcHepper.JDBCHepper;
import java.util.ArrayList;
import java.util.List;
import com.edusys.DAO.KhoaHocDAO;
import com.edusys.DAO.NguoiHocDAO;
import com.edusys.Entity.KhoaHoc;
import javax.swing.table.DefaultTableModel;
import com.edusys.DAO.thongKeDAO;
import com.edusys.Entity.NguoiHoc;
import com.edusys.Entity.HocVien;
import com.edusys.DAO.HocVienDAO;
import java.sql.ResultSet;
import java.util.Date;

/**
 *
 * @author DELL
 */
public class QuanLi_ThongKe extends javax.swing.JDialog {

    /**
     * Creates new form thongKeDiemJDialog
     */
    List<Integer> listNam = new ArrayList<>();
//    List<Object[]> listDiem = new ArrayList<>();

    DefaultTableModel modelDiem;
    DefaultTableModel modelNguoiHoc;
    DefaultTableModel modelChuyenDe;
    DefaultTableModel modelDoanhThu;
    NguoiHocDAO nhDAO = new NguoiHocDAO();
    KhoaHocDAO khDAO = new KhoaHocDAO();
    thongKeDAO tkDAO = new thongKeDAO();
    HocVienDAO hvDAO = new HocVienDAO();

    public QuanLi_ThongKe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        modelDiem = (DefaultTableModel) tblBangDiem.getModel();
        modelNguoiHoc = (DefaultTableModel) tblNguoiHoc.getModel();
        modelChuyenDe = (DefaultTableModel) tblChuyenDe.getModel();
        modelDoanhThu = (DefaultTableModel) tblDoanhTHu.getModel();
        jTabbedPane1.setSelectedIndex(EduSysJFrame.tabThongKe);
        listNam = tkDAO.selectYear();

        System.out.println(listNam);
        fillToCboNam();
        fillCboKhoaHoc();
        fillNHbyslq();
        fillChuyenDeBysql();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cboKhoaHoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNguoiHoc = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChuyenDe = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cboNamDoangThu = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDoanhTHu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys - Thống kê Điểm");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Khóa Học"));

        cboKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cboKhoaHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cboKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        tblBangDiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã người học", "Họ tên", "Điểm", "Xếp Loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangDiem.setRowHeight(24);
        jScrollPane1.setViewportView(tblBangDiem);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bảng Điểm", jPanel1);

        tblNguoiHoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Năm", "Số người học", "Đăng kí sớm nhất", "Đăng kí muộn nhất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNguoiHoc.setRowHeight(24);
        jScrollPane2.setViewportView(tblNguoiHoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lượng Người Học", jPanel2);

        tblChuyenDe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblChuyenDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Chuyên Đề", "SL HV", "Điểm TN", "Điểm CN", "Điểm TB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChuyenDe.setRowHeight(24);
        jScrollPane3.setViewportView(tblChuyenDe);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Chuyên Đề", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Năm"));

        cboNamDoangThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamDoangThuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cboNamDoangThu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cboNamDoangThu, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        tblDoanhTHu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblDoanhTHu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Chuyên Đề", "SL khóa học", "SL học viên", "Học phí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoanhTHu.setRowHeight(24);
        jScrollPane4.setViewportView(tblDoanhTHu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doanh Thu", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        EduSysJFrame.lblStatus.setText("Hệ Thống Quản Lí Đào Tạo EduSys");
    }//GEN-LAST:event_formWindowClosed

    private void cboKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaHocActionPerformed
//        listDiem = tkDAO.seletctDiem(Integer.parseInt(cboKhoaHoc.getSelectedItem() + ""));
        int ma = Integer.parseInt(cboKhoaHoc.getSelectedItem().toString());
        fillTableDiem(ma);
    }//GEN-LAST:event_cboKhoaHocActionPerformed

    private void cboNamDoangThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamDoangThuActionPerformed
        int year = Integer.parseInt(cboNamDoangThu.getSelectedItem().toString());
        fillTableDoanhThu(year);
    }//GEN-LAST:event_cboNamDoangThuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLi_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLi_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLi_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLi_ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLi_ThongKe dialog = new QuanLi_ThongKe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboKhoaHoc;
    private javax.swing.JComboBox<String> cboNamDoangThu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTable tblChuyenDe;
    private javax.swing.JTable tblDoanhTHu;
    private javax.swing.JTable tblNguoiHoc;
    // End of variables declaration//GEN-END:variables
    List<KhoaHoc> listKhoaHoc = khDAO.selectAll();
    List<NguoiHoc> listNguoiHoc = nhDAO.selectAll();
    List<HocVien> listHocVien = hvDAO.selectAll();

    private void fillToCboNam() {
        for (Integer in : listNam) {
            cboNamDoangThu.addItem(in + "");
        }
    }

    private void fillCboKhoaHoc() {
        for (KhoaHoc kh : listKhoaHoc) {
            cboKhoaHoc.addItem(kh.getMaKhoaHoc() + "");
        }
    }

    private void fillTableKhoaHoc(int makhoahoc) {
        modelDiem.setRowCount(0);
        for (KhoaHoc kh : listKhoaHoc) {
            if (kh.getMaKhoaHoc() == makhoahoc) {
                modelDiem.addRow(new Object[]{kh.getMaKhoaHoc(), "ấ"});
            }
        }
    }

    private String getXepLoai(int diem) {
        String xepLoai = "";
        if (diem <= 5) {
            xepLoai = "yếu";
        } else if (diem <= 7) {
            xepLoai = "khá";
        } else {
            xepLoai = "giỏi";
        }
        return xepLoai;
    }

    private void fillTableDiem(int ma) {
        modelDiem.setRowCount(0);
        for (HocVien hv : listHocVien) {
            if (hv.getMaKhoaHoc() == ma) {
                modelDiem.addRow(new Object[]{
                    getNguoiHoc(hv.getMaNguoiHoc()).getMaHocVien(),
                    getNguoiHoc(hv.getMaNguoiHoc()).getHotenHocVien(),
                    hv.getDiem(),
                    getXepLoai(hv.getDiem())
                });
            }

        }
    }

    private void fillTableNguoiHoc() {
        int countNguoiHoc = 0;
        modelNguoiHoc.setRowCount(0);
        for (NguoiHoc nh : listNguoiHoc) {
//            if(){}
            modelNguoiHoc.addRow(new Object[]{});
        }
    }

    private void fillTableChuyenDe() {

    }

    private NguoiHoc getNguoiHoc(String maNguoiHoc) {
        NguoiHoc getNH = new NguoiHoc();
        for (NguoiHoc nh : listNguoiHoc) {
            if (nh.getMaHocVien().equals(maNguoiHoc)) {
                getNH = nh;
                break;
            }
        }
        return getNH;
    }

    // test
    private void fillNHbyslq() {
        modelNguoiHoc.setRowCount(0);
        String sql = "select COUNT(mahocvien)  as soluongnguoihoc, YEAR(khoahoc.ngaykhaigiang), min(ngayDK) as dksomnhat, MAX(ngayDK) as dkmuonnhat\n"
                + "from hocvien join khoahoc on khoahoc.makhoahoc = hocvien.makhoahoc join nguoihoc on hocvien.manguoihoc =nguoihoc.manguoihoc\n"
                + "where hocvien.makhoahoc in(\n"
                + "			select distinct makhoahoc as soluongkhoahoc--,YEAR(ngaykhaigiang)-- trả về khóa học trong năm\n"
                + "			from khoahoc\n"
                + "			where YEAR(ngaykhaigiang)  in (select distinct YEAR(ngaykhaigiang) from khoahoc)--select * from hocvien\n"
                + "			)\n"
                + "group by  YEAR(khoahoc.ngaykhaigiang)";
        try {
            ResultSet rs = JDBCHepper.query(sql);
            while (rs.next()) {
                int soluongnguoihoc = rs.getInt(1);
                String nam = rs.getString(2);
                Date min = rs.getDate(3);
                Date max = rs.getDate(4);
//                System.out.println(soluongnguoihoc +" "+ nam +" "+min+" "+max);
                modelNguoiHoc.addRow(new Object[]{nam,soluongnguoihoc,  min, max});
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("loi query ok");
        }
    }

    private void fillChuyenDeBysql() {
        modelChuyenDe.setRowCount(0);
        String sql = "select  distinct chuyende.machuyende, COUNT(khoahoc.makhoahoc) as slkhoahoc,COUNT(hocvien.mahocvien) as slhocvien,MIN(diem) as mind,MAX(diem) as maxd\n"
                + "from chuyende left outer join khoahoc on chuyende.machuyende = khoahoc.machuyende left outer join hocvien on hocvien.makhoahoc = khoahoc.makhoahoc\n"
                + "where chuyende.machuyende in(\n"
                + "		select distinct machuyende from chuyende\n"
                + "		)\n"
                + "group by chuyende.machuyende";
        try {
            ResultSet rs = JDBCHepper.query(sql);
            while (rs.next()) {
                String tenChuyenDe = rs.getString(1);
                int sl = rs.getInt(3);
                int mindiem = rs.getInt(4);
                int maxdiem = rs.getInt(5);
//                System.out.println(tenChuyenDe +" "+sl +" " + mindiem+" "+maxdiem);
                modelChuyenDe.addRow(new Object[]{tenChuyenDe,sl,mindiem,maxdiem,getTB(mindiem, maxdiem)});
            }
        } catch (Exception e) {
        }
    }
    private float getTB(int a, int b){
        float tb=(a+b)/2;
        
        return tb;
    }
    
    private void fillTableDoanhThu(int year){
        modelDoanhThu.setRowCount(0);
        String sql="{CALL select_DoanhThu (?)}";
        try {
            ResultSet rs = JDBCHepper.query(sql,year);
            while(rs.next()){
                String ten = rs.getString(1);
                int slKhoaHoc = rs.getInt(2);
                int slHocVien = rs.getInt(3);
                float hocPhi = rs.getFloat(4);
                
                modelDoanhThu.addRow(new Object[]{ten,slHocVien,slHocVien,hocPhi});
//                System.out.println(ten);
            }
            rs.getStatement().close();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("loi query obj");
        }
    }

}
